### PR TITLE
Changed WMIC to non-deprecated alternatives

### LINKED ISSUE #254: Windows 11 24H2 26100 has WMIC disabled by default
When installing an agent on Windows 11 24H2 26100 (Early preview), I receive the error:

`..\microscript\ILibDuktape_ScriptContainer.c:1667 (0,0) uncaught: ‘cannot read property \x27split\x27 of null`

I can't verify for sure that this is coming from WMIC missing because it doesn't give me a stack trace, but meshagent does use WMIC and attempt to parse the results, and it is what is in common with the devices on which I have seen this occur, so it seems probable.

WMIC was deprecated in 2021, and it seems like the chickens are finally coming home to roost on this. It also looks like it may need to be replaced with a powershell script, according to [this blog post](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/ba-p/4039242).

### PR DESCRIPTION
**Pull request by HuFlungDu**
This is a companion pull request with: https://github.com/Ylianst/MeshCentral/pull/6320

Fixes #254 

In this PR, I modified the JS module code containing the wmic changes and the one C file with wmic hardcoded in it. I did not recompile the modules, as I'm not sure of the procedure for doing so, though I did compile them locally for testing, they just didn't come out with all the comments and ifdefs and whatnot.

### CODE REVIEW

**Comment by si458** [comment]
this is another reason we cant switch yet to using powershell https://github.com/Ylianst/MeshAgent/issues/256
it seems to spawn powershells over and over again!

**Comment by si458** [comment]
just done a quick compile/test
and can confirm this fixes the `uncaught: 'cannot read property \x27split\x27 of null'` error also!
the error stems from the `util-language.js` file!!!

**Comment by HuFlungDu** [comment]
I was looking into the source code; is it possible to do this with modules/win-wmi.js?

Looks like it's mostly a query library, so it doesn't handle everything, but it should get rid of a lot of the powershell invocations.

**Comment by si458** [comment]
@HuFlungDu erm possibly yes!
as we already use it inside the meshcore and a few other files
```
ret = require('win-wmi').query('ROOT\\CIMV2', 'SELECT * FROM Win32_ComputerSystem', ['Name', 'Domain'])[0];
...
values = require('win-wmi').query('ROOT\\CIMV2', "SELECT * FROM Win32_PhysicalMemory");
...
v = require('win-wmi').query('ROOT\\CIMV2\\Security\\MicrosoftVolumeEncryption', 'SELECT * FROM Win32_EncryptableVolume');
```

i wont merge this just yet but it does give us ideas to look into using the `win-wmi` instead tho!

**Comment by si458** [comment]
ok so i can confirm the win-wmi works! and even fixes the crashing on startup!
replacement section of code below for `util-language.js` inside the `getCurrent` function
```
// On windows we will use WMI to get the LCID. 
if (process.platform == 'win32') {
  var tokens = require('win-wmi').query('ROOT\\CIMV2', 'SELECT OSLanguage FROM Win32_OperatingSystem', ['OSLanguage']);
  if (tokens[0]) {
    // Convert LCID to language string
    return (toLang(tokens[0]['OSLanguage'].toString()));
  } else {
    // fallback to en-us to avoid crashing
    return ("en-us");
  }
}
```
so my plan will be next week to take this PR and the PR from meshcentral and replace everything using wmic
with win-wmi!
unless u want to beat me to it!

**Comment by si458** [comment]
ok so ive done commits to fix the `split` issue on startup and also replace the `wmic service` with `net` commands
others will follow!

**Comment by si458** [comment]
i cannot thank you enough for the help!
ive also learnt how to build the polyfills and its working a treat now!
commits below
https://github.com/Ylianst/MeshAgent/commit/105da7dbfae9b32d5be67bbe12b1dee5fda400c9
https://github.com/Ylianst/MeshAgent/commit/435bccd1eb335b2d54ad2057d8c40a477201df51
https://github.com/Ylianst/MeshAgent/commit/d08c5ceb711d8c1e21ffb4b5f8f58f3f5e39bcf0

**Comment by HuFlungDu** [comment]
Looks awesome, thanks Simon! And thanks for the info about how to build the modules and such, that'll make any changes we need much easier.

**Pull request closed without merging**
