### PR TITLE
Added permissions validation on start for macOS

### PR DESCRIPTION
**Pull request by jpros**
Added permissions validation on start for macOS: Screen Recording, Accessibility, and Full Disk Access.

It uses a Private API from Apple for Full Disk Access, which might not work forever, but for the current versions is working. The FDA code is converted from Objective-C from https://github.com/MacPaw/PermissionsKit

### CODE REVIEW

**Comment by si458** [comment]
@Ylianst i think this needs to be reverted as you cant build the agent on linux anymore
```
/usr/bin/ld: meshcore/agentcore.o: in function `MeshAgent_Create':
/root/MeshAgent/meshcore/agentcore.c:4495: undefined reference to `kvm_check_permission'
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:650: meshagent_x86-64] Error 1
make[1]: Leaving directory '/root/MeshAgent'
make: *** [makefile:751: linux] Error 2
```

**Comment by jpros** [comment]
@si458 I'll check that.

**Comment by si458** [comment]
@jpros did you have any look with this at all?

**Comment by jpros** [comment]
@si458 fixed on PR: https://github.com/Ylianst/MeshAgent/pull/215

**Comment by si458** [comment]
hey, just managed to use opencore legacy to upgrade my old macbook pro from 10.15 to 11.7,
i can finally build the OSX binary for intel now! still need an M mac for arm versions but its a start!

one issue ive spotted is when you first connect it requests screen recording as expected,
you click open system preferences, unlock, tick box, GOOD!?

but it then never asks for the accessability permissions until you disconnect and then reconnect? is this expected?

also if you click deny, then disconnect and reconnect, you are never prompted for the permissions again? again is this expected?

its going to be more of a DOCS HOW TO, if thats the case

**Pull request merged**
